# Generated by Django 4.0.5 on 2022-07-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='type',
        ),
        migrations.AddField(
            model_name='work',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='works', to='webapp.type'),
        ),
    ]
