# Generated by Django 4.0.5 on 2022-07-25 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='webapp.project', verbose_name='Проект'),
        ),
    ]
