# Generated by Django 4.0.5 on 2022-07-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_work_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
