# Generated by Django 4.0.5 on 2022-07-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_project_created_at_remove_project_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='works',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='webapp.work', verbose_name='Задача'),
        ),
    ]
