# Generated by Django 4.0.5 on 2022-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_work_projects_project_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='projects', to='webapp.project'),
        ),
    ]
