# Generated by Django 4.0.5 on 2022-07-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_work_project_alter_project_works'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='works',
        ),
        migrations.AddField(
            model_name='work',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='webapp.project', verbose_name='Проект'),
        ),
    ]
