# Generated by Django 4.0.5 on 2022-07-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_project_works_work_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='projects',
        ),
        migrations.AddField(
            model_name='work',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webapp.project', verbose_name='Проект'),
        ),
    ]
