# Generated by Django 4.0.5 on 2022-08-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_project_user_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_users_in_project', 'Добавление пользователей в проект')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
